In [10]:
import torch
import torch.nn as nn
from torch.nn import functional as F
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)
block_size = 8
batch_size = 1
max_iters = 10000
learning_rate = 3e-4
eval_iters = 250

cpu


In [2]:
with open('wizard_of_oz.txt', 'r', encoding='utf-8') as f:
    text = f.read()
chars = sorted(set(text))
vocabulary_size = len(chars)

In [3]:
string_to_int = { ch:i for i,ch in enumerate(chars) }
int_to_string = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])

data = torch.tensor(encode(text), dtype=torch.long)
print(data[:100])

tensor([92, 49, 66, 63,  1, 45, 76, 73, 68, 63, 61, 78,  1, 36, 79, 78, 63, 72,
        60, 63, 76, 65,  1, 63, 31, 73, 73, 69,  1, 73, 64,  1, 33, 73, 76, 73,
        78, 66, 83,  1, 59, 72, 62,  1, 78, 66, 63,  1, 52, 67, 84, 59, 76, 62,
         1, 67, 72,  1, 44, 84,  0,  1,  1,  1,  1,  0, 49, 66, 67, 77,  1, 63,
        31, 73, 73, 69,  1, 67, 77,  1, 64, 73, 76,  1, 78, 66, 63,  1, 79, 77,
        63,  1, 73, 64,  1, 59, 72, 83, 73, 72])


In [4]:
n = int(0.8*len(data))
train_data = data[:n]
val_data = data[n:]

def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

x, y = get_batch('train')
print('inputs:')
print(x.shape)
print(x)
print('targets')
print(y)

inputs:
torch.Size([1, 8])
tensor([[ 0,  0,  3, 52, 66, 83, 13,  1]])
targets
tensor([[ 0,  3, 52, 66, 83, 13,  1, 67]])


In [5]:
block_size = 8

x = train_data[:block_size]
y = train_data[1:block_size + 1]

for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print("when input is", context, "target is", target)


when input is tensor([92]) target is tensor(49)
when input is tensor([92, 49]) target is tensor(66)
when input is tensor([92, 49, 66]) target is tensor(63)
when input is tensor([92, 49, 66, 63]) target is tensor(1)
when input is tensor([92, 49, 66, 63,  1]) target is tensor(45)
when input is tensor([92, 49, 66, 63,  1, 45]) target is tensor(76)
when input is tensor([92, 49, 66, 63,  1, 45, 76]) target is tensor(73)
when input is tensor([92, 49, 66, 63,  1, 45, 76, 73]) target is tensor(68)


In [6]:
# ...existing code...
@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()   # was loss.mean()
    model.train()                  # moved outside the split loop
    return out                     # moved outside the split loop
# ...existing code...

In [7]:
class BigramLanguageModel(nn.Module):

    def __init__(self, vocabulary_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocabulary_size, vocabulary_size)

    def forward(self, index, targets=None):

        logits = self.token_embedding_table(index)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape

            logits = logits.reshape(B * T, C)
            targets = targets.reshape(B * T)

            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, index, max_new_tokens):

        for _ in range(max_new_tokens):

            logits, loss = self.forward(index)

            logits = logits[:, -1, :]

            probs = F.softmax(logits, dim=-1)

            index_next = torch.multinomial(probs, num_samples=1)

            index = torch.cat((index, index_next), dim=1)

        return index


model = BigramLanguageModel(vocabulary_size)
m = model.to(device)

context = torch.zeros((1, 1), dtype=torch.long, device=device)

generated_chars = decode(
    m.generate(context, max_new_tokens=500)[0].tolist()
)


    
print(context)
print(target)
print(int_to_string[context.item()])
print(int_to_string[target.item()])


first_letter = generated_chars[1]
print(first_letter)

token = string_to_int[first_letter]
print(token)


print(f" Generated Chars.start {generated_chars}")





tensor([[0]])
tensor(68)


j
0
17
 Generated Chars.start 
0/vZp6/-mJ—”O j-‘].
?”p]kQYLq™o444BW'HJgm;bdWV'8cfR™!ZAAQL1KV_b
/
-‘™$C’9&,s,dWLf!_(,&f3D#™&g_bL16vHJp”G*%lk‘eJj_”s!3';$;;'8Fpjr*-‘’IX#z&M”a0qb
q™“ZVXg”/23Rvh';”F•F,;u7’H/TogiubYUC44Hv(cuFPibYod7’lFx"”!
3x&hSp']cf)BJLSWJQ5k’R%C)2VXe•hb(D;!dle_O&VBUL+EdW
$&V™n.3[#Fd—]
#v(!’%‘—b—w7•L)2]'TAAAZtuHqsPq
3/Vu776C%[*; 
gb([HJ:Irf16jvH“Z#,qi"“u)NHt(vq16"YQ)uOl$2#KTt(lCCD+r#I:'R4”/T'%™Gzadjy,BOpC7CiEY—sY•H,TaO;™$7Xi/0h"QwK2AVr%4[
Kj']."J-iu:_b[#S+c8tbC5+“;!Zgk)d7yAC,j™20.yQ”T0ksz•™w$‘KV9jvg#6-JJ


In [11]:
# ...existing code...
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

# keep history outside the training loop
list_step = []
list_data = []
list_generated_chars = []

for iter in range(max_iters):
    losses = estimate_loss()
    if iter % eval_iters == 0:
        print(f"step: {iter}, train: {losses['train']}")
        list_step.append(iter)
        list_generated_chars.append(generated_chars)
        list_data.append(losses['train'])

    xb, yb = get_batch('train')

    logits, loss = model(xb, yb)

    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())

# safe check before using history
if list_data:
    smallest = 10
    number = 0
    for idx, value in enumerate(list_data):
        if value < smallest:
            smallest = value
            number = idx
    print(list_generated_chars[number])
else:
    print("No evaluation data collected (list_data is empty).")
# ...existing code...

step: 0, train: 4.839021682739258
step: 250, train: 4.750339984893799
step: 500, train: 4.670037269592285
step: 750, train: 4.650110721588135
step: 1000, train: 4.599109172821045
step: 1250, train: 4.570114612579346
step: 1500, train: 4.552022457122803
step: 1750, train: 4.514645099639893
step: 2000, train: 4.472713947296143
step: 2250, train: 4.440323352813721
step: 2500, train: 4.42318058013916
step: 2750, train: 4.37825870513916
step: 3000, train: 4.363767623901367
step: 3250, train: 4.250447750091553
step: 3500, train: 4.285976886749268
step: 3750, train: 4.219543933868408
step: 4000, train: 4.186239719390869
step: 4250, train: 4.186553001403809
step: 4500, train: 4.118711948394775
step: 4750, train: 4.089188098907471
step: 5000, train: 4.072065353393555
step: 5250, train: 4.051109790802002
step: 5500, train: 4.041740894317627
step: 5750, train: 3.9878787994384766
step: 6000, train: 3.9919826984405518
step: 6250, train: 3.918233871459961
step: 6500, train: 3.886382579803467
step: 6

In [9]:
context = torch.zeros((1, 1), dtype=torch.long, device=device)
generated_chars = decode(m.generate(context, max_new_tokens=500)[0].tolist())
print(generated_chars)


P:8+
$iJ]nvWm0&ob
BJb
G%1 _gbA6
nDR™/]'Tz™:rWp‘aQ•M)n•iwAJcpjl:q/kmPdX%M8q—S8d]lSVQ0j']-'x8‘™jIk’0M_“oW$v9i,"inv “N?'m;:N1ODqKSjPrjFEKYkGWH)?w(u!Z”%['cM,)C“Zx]8“iC2z%IK1 [$]C$VXODIFsH6[33R™Gk0Qw”;YW_x]bAQT%P,8“f’#+™3 a_(6/FcWp”IU:1sP2p$j_ddAR1 s#‘e0.$hV_:&,0—!QrN??
A3Lu"CFLUh•“u3LC'l$:F_#8“l—vq."/EB,Y“'TObvvD*g”•ts1’9]C'W5E$m™
?T:#.u t_o_"qgqD".P:';w_‘peCipEEaVX’HFPa8m1I!•tJA/-3M6)N9w’ gT)4ks1[w’GQ_xJ“"t244s4('$,j;!6"ls!55K1KRM"”•tw,v]3_(,Inp&‘ExEPLQwKI_a#xZ"EY-*$u’]J6U“ZmVYpHCB1™“3$z“
