In [45]:
import torch
import torch.nn as nn
from torch.nn import functional as F

device = 'mps' if torch.backends.mps.is_available() else 'cpu'
print(device)

block_size = 128
batch_size = 32        # bring this back down, each sequence is now 4x longer
max_iters = 5000
learning_rate = 1e-3
eval_iters = 100
eval_interval = 500
n_embd = 128
n_heads = 4
n_layers = 4
dropout = 0.2

mps


In [46]:
with open('wizard_of_oz.txt', 'r', encoding='utf-8') as f:
    text = f.read()
chars = sorted(set(text))
vocabulary_size = len(chars)

In [47]:
string_to_int = { ch:i for i,ch in enumerate(chars) }
int_to_string = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])

data = torch.tensor(encode(text), dtype=torch.long)
print(data[:100])

tensor([92, 49, 66, 63,  1, 45, 76, 73, 68, 63, 61, 78,  1, 36, 79, 78, 63, 72,
        60, 63, 76, 65,  1, 63, 31, 73, 73, 69,  1, 73, 64,  1, 33, 73, 76, 73,
        78, 66, 83,  1, 59, 72, 62,  1, 78, 66, 63,  1, 52, 67, 84, 59, 76, 62,
         1, 67, 72,  1, 44, 84,  0,  1,  1,  1,  1,  0, 49, 66, 67, 77,  1, 63,
        31, 73, 73, 69,  1, 67, 77,  1, 64, 73, 76,  1, 78, 66, 63,  1, 79, 77,
        63,  1, 73, 64,  1, 59, 72, 83, 73, 72])


In [48]:
n = int(0.8*len(data))
train_data = data[:n]
val_data = data[n:]

def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

x, y = get_batch('train')
print('inputs:')
print(x.shape)
print(x)
print('targets')
print(y)

inputs:
torch.Size([32, 128])
tensor([[79,  1, 61,  ..., 13,  3,  1],
        [72, 61, 63,  ...,  3,  1, 76],
        [63, 76, 83,  ..., 60, 79, 78],
        ...,
        [65, 66, 78,  ..., 67, 63,  1],
        [73, 78, 66,  ..., 81, 73, 73],
        [ 0, 81, 66,  ..., 79, 77, 63]], device='mps:0')
targets
tensor([[ 1, 61, 59,  ...,  3,  1, 77],
        [61, 63, 15,  ...,  1, 76, 63],
        [76, 83,  0,  ..., 79, 78,  1],
        ...,
        [66, 78, 15,  ..., 63,  1, 62],
        [78, 66, 83,  ..., 73, 73, 62],
        [81, 66, 63,  ..., 77, 63,  1]], device='mps:0')


In [49]:
block_size = 8

x = train_data[:block_size]
y = train_data[1:block_size + 1]

for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print("when input is", context, "target is", target)


when input is tensor([92]) target is tensor(49)
when input is tensor([92, 49]) target is tensor(66)
when input is tensor([92, 49, 66]) target is tensor(63)
when input is tensor([92, 49, 66, 63]) target is tensor(1)
when input is tensor([92, 49, 66, 63,  1]) target is tensor(45)
when input is tensor([92, 49, 66, 63,  1, 45]) target is tensor(76)
when input is tensor([92, 49, 66, 63,  1, 45, 76]) target is tensor(73)
when input is tensor([92, 49, 66, 63,  1, 45, 76, 73]) target is tensor(68)


In [50]:
# ...existing code...
@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()   # was loss.mean()
    model.train()                  # moved outside the split loop
    return out                     # moved outside the split loop
# ...existing code...

In [51]:
class Head(nn.Module):
    def __init__(self, head_size):
        super().__init__()
        self.key   = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B, T, C = x.shape
        k = self.key(x)
        q = self.query(x)
        wei = q @ k.transpose(-2, -1) * C**-0.5
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf'))
        wei = F.softmax(wei, dim=-1)
        wei = self.dropout(wei)
        v = self.value(x)
        return wei @ v


class MultiHeadAttention(nn.Module):
    def __init__(self, n_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(n_heads)])
        self.proj  = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out


class FeedForward(nn.Module):
    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)


class Block(nn.Module):
    def __init__(self, n_embd, n_heads):
        super().__init__()
        head_size = n_embd // n_heads
        self.sa   = MultiHeadAttention(n_heads, head_size)
        self.ff   = FeedForward(n_embd)
        self.ln1  = nn.LayerNorm(n_embd)
        self.ln2  = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ff(self.ln2(x))
        return x


class BigramLanguageModel(nn.Module):
    def __init__(self, vocabulary_size):
        super().__init__()
        self.token_embedding_table    = nn.Embedding(vocabulary_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks  = nn.Sequential(*[Block(n_embd, n_heads) for _ in range(n_layers)])
        self.ln_f    = nn.LayerNorm(n_embd)
        self.lm_head = nn.Linear(n_embd, vocabulary_size)

    def forward(self, index, targets=None):
        B, T = index.shape
        tok_emb = self.token_embedding_table(index)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device))
        x = tok_emb + pos_emb
        x = self.blocks(x)
        x = self.ln_f(x)
        logits = self.lm_head(x)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits  = logits.reshape(B * T, C)
            targets = targets.reshape(B * T)
            loss    = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, index, max_new_tokens):
        for _ in range(max_new_tokens):
            index_cond = index[:, -block_size:]
            logits, loss = self.forward(index_cond)
            logits = logits[:, -1, :]
            probs  = F.softmax(logits, dim=-1)
            index_next = torch.multinomial(probs, num_samples=1)
            index = torch.cat((index, index_next), dim=1)
        return index


model = BigramLanguageModel(vocabulary_size)
m = model.to(device)

context = torch.zeros((1, 1), dtype=torch.long, device=device)
generated_chars = decode(m.generate(context, max_new_tokens=500)[0].tolist())
print(generated_chars)


%wpJR]RoGc—n,•™,wsO”qmt7%W!d:,M)vfKyqk7—mw3PK7w7'’f/IgjK‘
g7XDPbu”N.m‘-zSGT•Qq0*ng+v™!WFz#WRzAH4Zmo7$#vSiru bj'eo•[%gSUr.oI7;vBp+A”SYK—nTb(uY™PSxsvt!o—;_l•$6x.a0H[[(-ig0O45fa$0sTir7]v9,tzF#J”t+3Fogt!lSaUk”A”F0n”Kra‘1•c:7OOY4N]”.IS+.z•7H"'e
q!TmaR6•H"8")+ C_rh!1hr[W!g/0KNx"c)HMf*’oA•UxPnWlHpJ!“oh;ox]/dtWIS B.OxihcAQr‘.#)T H7?ai7fn"gvGt+3’7:S6x$&RzZq‘n#HZ_]cBG5OTJl.e6p;iF•s-r'R7
U],cABex"nSZC“c”aSYo'S
$™ao0)at;U'7'K]e(_™5QvrApOpeep7uIz#Z%i$XearWM7Q"ND!Ym+‘&"euwIgu76r”F•),6]z(”r™x7cA4Wg5?nSnxi


In [52]:
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

list_step = []
list_data = []
list_generated_chars = []

for iter in range(max_iters):
    xb, yb = get_batch('train')
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

    if iter % eval_iters == 0:
        losses = estimate_loss()
        print(f"step: {iter}, train: {losses['train']:.4f}, val: {losses['val']:.4f}")
        list_step.append(iter)
        list_data.append(losses['train'])
        context = torch.zeros((1, 1), dtype=torch.long, device=device)
        generated_chars = decode(m.generate(context, max_new_tokens=100)[0].tolist())
        list_generated_chars.append(generated_chars)

print(f"\nFinal loss: {loss.item():.4f}")

if list_data:
    best_idx = list_data.index(min(list_data))
    print(f"\nBest generated sample (step {list_step[best_idx]}):")
    print(list_generated_chars[best_idx])
else:
    print("No evaluation data collected.")

step: 0, train: 4.1672, val: 4.1736
step: 100, train: 2.4518, val: 2.6697
step: 200, train: 2.3156, val: 2.5332
step: 300, train: 2.2245, val: 2.4741
step: 400, train: 2.1603, val: 2.4004
step: 500, train: 2.1030, val: 2.3516
step: 600, train: 2.0744, val: 2.3156
step: 700, train: 2.0093, val: 2.2818
step: 800, train: 2.0065, val: 2.2684
step: 900, train: 1.9906, val: 2.2660
step: 1000, train: 1.9543, val: 2.2557
step: 1100, train: 1.9430, val: 2.2407
step: 1200, train: 1.9466, val: 2.2202
step: 1300, train: 1.8978, val: 2.1881
step: 1400, train: 1.8766, val: 2.2030
step: 1500, train: 1.9200, val: 2.1960
step: 1600, train: 1.8563, val: 2.1599
step: 1700, train: 1.8551, val: 2.1578
step: 1800, train: 1.8637, val: 2.1710
step: 1900, train: 1.8551, val: 2.1691
step: 2000, train: 1.8319, val: 2.1524
step: 2100, train: 1.8419, val: 2.1498
step: 2200, train: 1.8414, val: 2.1245
step: 2300, train: 1.8313, val: 2.1637
step: 2400, train: 1.8082, val: 2.1540
step: 2500, train: 1.8103, val: 2.153

In [53]:
context = torch.zeros((1, 1), dtype=torch.long, device=device)
generated_chars = decode(m.generate(context, max_new_tokens=500)[0].tolist())
print(generated_chars)


They prove mounds roofs'ze desten, for four fastly-Magicl, me Oz; I'vur
Cona no the any days wenry his them of them. [Illustous tloninkly. Intair, and inds one
Cart up no lawed eat
to retue hers
        *    THE OF V. Het.

[Illustre at.

"Her.

"As, and
worned----wor flied to the nose to tok on ceaties bode then abouts ventumble it of the verly, which Thouse onh the bow ead trust and too shed mor untry horse
doe youwe're and voies trough and
any reptise whet in Oz.. Let cleard sharp untratess i
